server:
  port: 9301

spring:
  application:
    name: eureka-provider
eureka:
  instance:
    prefer-ip-address: true # 注册服务的时候使用服务的IP地址
  client:
    service-url:
      defaultZone: http://localhost:9300/eureka/
